/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { WistiaError } from "./wistiaerror.js";

/**
 * Domain not found
 */
export type DeleteAllowedDomainsDomainNotFoundErrorData = {
  error?: string | undefined;
};

/**
 * Domain not found
 */
export class DeleteAllowedDomainsDomainNotFoundError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: DeleteAllowedDomainsDomainNotFoundErrorData;

  constructor(
    err: DeleteAllowedDomainsDomainNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "DeleteAllowedDomainsDomainNotFoundError";
  }
}

/** @internal */
export const DeleteAllowedDomainsDomainNotFoundError$inboundSchema: z.ZodType<
  DeleteAllowedDomainsDomainNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DeleteAllowedDomainsDomainNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DeleteAllowedDomainsDomainNotFoundError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const DeleteAllowedDomainsDomainNotFoundError$outboundSchema: z.ZodType<
  DeleteAllowedDomainsDomainNotFoundError$Outbound,
  z.ZodTypeDef,
  DeleteAllowedDomainsDomainNotFoundError
> = z.instanceof(DeleteAllowedDomainsDomainNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteAllowedDomainsDomainNotFoundError$ {
  /** @deprecated use `DeleteAllowedDomainsDomainNotFoundError$inboundSchema` instead. */
  export const inboundSchema =
    DeleteAllowedDomainsDomainNotFoundError$inboundSchema;
  /** @deprecated use `DeleteAllowedDomainsDomainNotFoundError$outboundSchema` instead. */
  export const outboundSchema =
    DeleteAllowedDomainsDomainNotFoundError$outboundSchema;
  /** @deprecated use `DeleteAllowedDomainsDomainNotFoundError$Outbound` instead. */
  export type Outbound = DeleteAllowedDomainsDomainNotFoundError$Outbound;
}
