/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type DeleteChannelsChannelHashedIdInternalServerErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class DeleteChannelsChannelHashedIdInternalServerError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: DeleteChannelsChannelHashedIdInternalServerErrorData;

  constructor(
    err: DeleteChannelsChannelHashedIdInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "DeleteChannelsChannelHashedIdInternalServerError";
  }
}

/**
 * Forbidden, token is valid but account does not have access to feature
 */
export type DeleteChannelsChannelHashedIdForbiddenErrorData = {
  error?: string | undefined;
};

/**
 * Forbidden, token is valid but account does not have access to feature
 */
export class DeleteChannelsChannelHashedIdForbiddenError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: DeleteChannelsChannelHashedIdForbiddenErrorData;

  constructor(
    err: DeleteChannelsChannelHashedIdForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "DeleteChannelsChannelHashedIdForbiddenError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type DeleteChannelsChannelHashedIdUnauthorizedErrorData = {
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class DeleteChannelsChannelHashedIdUnauthorizedError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: DeleteChannelsChannelHashedIdUnauthorizedErrorData;

  constructor(
    err: DeleteChannelsChannelHashedIdUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "DeleteChannelsChannelHashedIdUnauthorizedError";
  }
}

/** @internal */
export const DeleteChannelsChannelHashedIdInternalServerError$inboundSchema:
  z.ZodType<
    DeleteChannelsChannelHashedIdInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new DeleteChannelsChannelHashedIdInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const DeleteChannelsChannelHashedIdForbiddenError$inboundSchema:
  z.ZodType<
    DeleteChannelsChannelHashedIdForbiddenError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new DeleteChannelsChannelHashedIdForbiddenError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const DeleteChannelsChannelHashedIdUnauthorizedError$inboundSchema:
  z.ZodType<
    DeleteChannelsChannelHashedIdUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new DeleteChannelsChannelHashedIdUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });
