/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type FiveHundredErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class FiveHundredError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: FiveHundredErrorData;

  constructor(
    err: FiveHundredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "FiveHundredError";
  }
}

/** @internal */
export const FiveHundredError$inboundSchema: z.ZodType<
  FiveHundredError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new FiveHundredError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type FiveHundredError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const FiveHundredError$outboundSchema: z.ZodType<
  FiveHundredError$Outbound,
  z.ZodTypeDef,
  FiveHundredError
> = z.instanceof(FiveHundredError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FiveHundredError$ {
  /** @deprecated use `FiveHundredError$inboundSchema` instead. */
  export const inboundSchema = FiveHundredError$inboundSchema;
  /** @deprecated use `FiveHundredError$outboundSchema` instead. */
  export const outboundSchema = FiveHundredError$outboundSchema;
  /** @deprecated use `FiveHundredError$Outbound` instead. */
  export type Outbound = FiveHundredError$Outbound;
}
