/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { WistiaError } from "./wistiaerror.js";

/**
 * Bad request
 */
export type FourHundredErrorData = {
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;
};

/**
 * Bad request
 */
export class FourHundredError extends WistiaError {
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: FourHundredErrorData;

  constructor(
    err: FourHundredErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "FourHundredError";
  }
}

/** @internal */
export const FourHundredError$inboundSchema: z.ZodType<
  FourHundredError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new FourHundredError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type FourHundredError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const FourHundredError$outboundSchema: z.ZodType<
  FourHundredError$Outbound,
  z.ZodTypeDef,
  FourHundredError
> = z.instanceof(FourHundredError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace FourHundredError$ {
  /** @deprecated use `FourHundredError$inboundSchema` instead. */
  export const inboundSchema = FourHundredError$inboundSchema;
  /** @deprecated use `FourHundredError$outboundSchema` instead. */
  export const outboundSchema = FourHundredError$outboundSchema;
  /** @deprecated use `FourHundredError$Outbound` instead. */
  export type Outbound = FourHundredError$Outbound;
}
