/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { WistiaError } from "./wistiaerror.js";

/**
 * Analytics service is temporarily unavailable
 */
export type GetAnalyticsMediasMediaIdLanguagesServiceUnavailableErrorData = {
  error?: string | undefined;
};

/**
 * Analytics service is temporarily unavailable
 */
export class GetAnalyticsMediasMediaIdLanguagesServiceUnavailableError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetAnalyticsMediasMediaIdLanguagesServiceUnavailableErrorData;

  constructor(
    err: GetAnalyticsMediasMediaIdLanguagesServiceUnavailableErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetAnalyticsMediasMediaIdLanguagesServiceUnavailableError";
  }
}

/**
 * Internal server error
 */
export type GetAnalyticsMediasMediaIdLanguagesInternalServerErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class GetAnalyticsMediasMediaIdLanguagesInternalServerError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetAnalyticsMediasMediaIdLanguagesInternalServerErrorData;

  constructor(
    err: GetAnalyticsMediasMediaIdLanguagesInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetAnalyticsMediasMediaIdLanguagesInternalServerError";
  }
}

/**
 * Forbidden, token is valid but account does not have access to feature
 */
export type GetAnalyticsMediasMediaIdLanguagesForbiddenErrorData = {
  error?: string | undefined;
};

/**
 * Forbidden, token is valid but account does not have access to feature
 */
export class GetAnalyticsMediasMediaIdLanguagesForbiddenError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetAnalyticsMediasMediaIdLanguagesForbiddenErrorData;

  constructor(
    err: GetAnalyticsMediasMediaIdLanguagesForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetAnalyticsMediasMediaIdLanguagesForbiddenError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type GetAnalyticsMediasMediaIdLanguagesUnauthorizedErrorData = {
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class GetAnalyticsMediasMediaIdLanguagesUnauthorizedError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetAnalyticsMediasMediaIdLanguagesUnauthorizedErrorData;

  constructor(
    err: GetAnalyticsMediasMediaIdLanguagesUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetAnalyticsMediasMediaIdLanguagesUnauthorizedError";
  }
}

/**
 * Bad request
 */
export type GetAnalyticsMediasMediaIdLanguagesBadRequestErrorData = {
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;
};

/**
 * Bad request
 */
export class GetAnalyticsMediasMediaIdLanguagesBadRequestError
  extends WistiaError
{
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetAnalyticsMediasMediaIdLanguagesBadRequestErrorData;

  constructor(
    err: GetAnalyticsMediasMediaIdLanguagesBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetAnalyticsMediasMediaIdLanguagesBadRequestError";
  }
}

/** @internal */
export const GetAnalyticsMediasMediaIdLanguagesServiceUnavailableError$inboundSchema:
  z.ZodType<
    GetAnalyticsMediasMediaIdLanguagesServiceUnavailableError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetAnalyticsMediasMediaIdLanguagesServiceUnavailableError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetAnalyticsMediasMediaIdLanguagesInternalServerError$inboundSchema:
  z.ZodType<
    GetAnalyticsMediasMediaIdLanguagesInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetAnalyticsMediasMediaIdLanguagesInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetAnalyticsMediasMediaIdLanguagesForbiddenError$inboundSchema:
  z.ZodType<
    GetAnalyticsMediasMediaIdLanguagesForbiddenError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetAnalyticsMediasMediaIdLanguagesForbiddenError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetAnalyticsMediasMediaIdLanguagesUnauthorizedError$inboundSchema:
  z.ZodType<
    GetAnalyticsMediasMediaIdLanguagesUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetAnalyticsMediasMediaIdLanguagesUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetAnalyticsMediasMediaIdLanguagesBadRequestError$inboundSchema:
  z.ZodType<
    GetAnalyticsMediasMediaIdLanguagesBadRequestError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetAnalyticsMediasMediaIdLanguagesBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });
