/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { WistiaError } from "./wistiaerror.js";

/**
 * Analytics service is temporarily unavailable
 */
export type GetAnalyticsMediasMediaIdTimeseriesServiceUnavailableErrorData = {
  error?: string | undefined;
};

/**
 * Analytics service is temporarily unavailable
 */
export class GetAnalyticsMediasMediaIdTimeseriesServiceUnavailableError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetAnalyticsMediasMediaIdTimeseriesServiceUnavailableErrorData;

  constructor(
    err: GetAnalyticsMediasMediaIdTimeseriesServiceUnavailableErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetAnalyticsMediasMediaIdTimeseriesServiceUnavailableError";
  }
}

/**
 * Internal server error
 */
export type GetAnalyticsMediasMediaIdTimeseriesInternalServerErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class GetAnalyticsMediasMediaIdTimeseriesInternalServerError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetAnalyticsMediasMediaIdTimeseriesInternalServerErrorData;

  constructor(
    err: GetAnalyticsMediasMediaIdTimeseriesInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetAnalyticsMediasMediaIdTimeseriesInternalServerError";
  }
}

/**
 * Forbidden, token is valid but account does not have access to feature
 */
export type GetAnalyticsMediasMediaIdTimeseriesForbiddenErrorData = {
  error?: string | undefined;
};

/**
 * Forbidden, token is valid but account does not have access to feature
 */
export class GetAnalyticsMediasMediaIdTimeseriesForbiddenError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetAnalyticsMediasMediaIdTimeseriesForbiddenErrorData;

  constructor(
    err: GetAnalyticsMediasMediaIdTimeseriesForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetAnalyticsMediasMediaIdTimeseriesForbiddenError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type GetAnalyticsMediasMediaIdTimeseriesUnauthorizedErrorData = {
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class GetAnalyticsMediasMediaIdTimeseriesUnauthorizedError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetAnalyticsMediasMediaIdTimeseriesUnauthorizedErrorData;

  constructor(
    err: GetAnalyticsMediasMediaIdTimeseriesUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetAnalyticsMediasMediaIdTimeseriesUnauthorizedError";
  }
}

/**
 * Bad request
 */
export type GetAnalyticsMediasMediaIdTimeseriesBadRequestErrorData = {
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;
};

/**
 * Bad request
 */
export class GetAnalyticsMediasMediaIdTimeseriesBadRequestError
  extends WistiaError
{
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetAnalyticsMediasMediaIdTimeseriesBadRequestErrorData;

  constructor(
    err: GetAnalyticsMediasMediaIdTimeseriesBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetAnalyticsMediasMediaIdTimeseriesBadRequestError";
  }
}

/** @internal */
export const GetAnalyticsMediasMediaIdTimeseriesServiceUnavailableError$inboundSchema:
  z.ZodType<
    GetAnalyticsMediasMediaIdTimeseriesServiceUnavailableError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetAnalyticsMediasMediaIdTimeseriesServiceUnavailableError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetAnalyticsMediasMediaIdTimeseriesInternalServerError$inboundSchema:
  z.ZodType<
    GetAnalyticsMediasMediaIdTimeseriesInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetAnalyticsMediasMediaIdTimeseriesInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetAnalyticsMediasMediaIdTimeseriesForbiddenError$inboundSchema:
  z.ZodType<
    GetAnalyticsMediasMediaIdTimeseriesForbiddenError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetAnalyticsMediasMediaIdTimeseriesForbiddenError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetAnalyticsMediasMediaIdTimeseriesUnauthorizedError$inboundSchema:
  z.ZodType<
    GetAnalyticsMediasMediaIdTimeseriesUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetAnalyticsMediasMediaIdTimeseriesUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetAnalyticsMediasMediaIdTimeseriesBadRequestError$inboundSchema:
  z.ZodType<
    GetAnalyticsMediasMediaIdTimeseriesBadRequestError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetAnalyticsMediasMediaIdTimeseriesBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });
