/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type GetBrandsBrandIdInternalServerErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class GetBrandsBrandIdInternalServerError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetBrandsBrandIdInternalServerErrorData;

  constructor(
    err: GetBrandsBrandIdInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetBrandsBrandIdInternalServerError";
  }
}

/**
 * Resource not found
 */
export type GetBrandsBrandIdNotFoundErrorData = {
  error?: string | undefined;
};

/**
 * Resource not found
 */
export class GetBrandsBrandIdNotFoundError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetBrandsBrandIdNotFoundErrorData;

  constructor(
    err: GetBrandsBrandIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetBrandsBrandIdNotFoundError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type GetBrandsBrandIdUnauthorizedErrorData = {
  /**
   * A machine-readable identifier for the specific authorization failure.
   */
  code?: operations.GetBrandsBrandIdCode | undefined;
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class GetBrandsBrandIdUnauthorizedError extends WistiaError {
  /**
   * A machine-readable identifier for the specific authorization failure.
   */
  code?: operations.GetBrandsBrandIdCode | undefined;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetBrandsBrandIdUnauthorizedErrorData;

  constructor(
    err: GetBrandsBrandIdUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.error != null) this.error = err.error;

    this.name = "GetBrandsBrandIdUnauthorizedError";
  }
}

/** @internal */
export const GetBrandsBrandIdInternalServerError$inboundSchema: z.ZodType<
  GetBrandsBrandIdInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetBrandsBrandIdInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetBrandsBrandIdNotFoundError$inboundSchema: z.ZodType<
  GetBrandsBrandIdNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetBrandsBrandIdNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetBrandsBrandIdUnauthorizedError$inboundSchema: z.ZodType<
  GetBrandsBrandIdUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: operations.GetBrandsBrandIdCode$inboundSchema.optional(),
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetBrandsBrandIdUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
