/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 84669cf40004
 */

import * as z from "zod/v3";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type GetBackgroundJobStatusBackgroundJobStatusIdInternalServerErrorData =
  {
    error?: string | undefined;
  };

/**
 * Internal server error
 */
export class GetBackgroundJobStatusBackgroundJobStatusIdInternalServerError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetBackgroundJobStatusBackgroundJobStatusIdInternalServerErrorData;

  constructor(
    err: GetBackgroundJobStatusBackgroundJobStatusIdInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name =
      "GetBackgroundJobStatusBackgroundJobStatusIdInternalServerError";
  }
}

/**
 * Background Job Status Not Associated with An Authorized Object
 */
export type GetBackgroundJobStatusBackgroundJobStatusIdForbiddenErrorData = {
  error?: string | undefined;
};

/**
 * Background Job Status Not Associated with An Authorized Object
 */
export class GetBackgroundJobStatusBackgroundJobStatusIdForbiddenError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetBackgroundJobStatusBackgroundJobStatusIdForbiddenErrorData;

  constructor(
    err: GetBackgroundJobStatusBackgroundJobStatusIdForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetBackgroundJobStatusBackgroundJobStatusIdForbiddenError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type GetBackgroundJobStatusBackgroundJobStatusIdUnauthorizedErrorData = {
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class GetBackgroundJobStatusBackgroundJobStatusIdUnauthorizedError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetBackgroundJobStatusBackgroundJobStatusIdUnauthorizedErrorData;

  constructor(
    err: GetBackgroundJobStatusBackgroundJobStatusIdUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetBackgroundJobStatusBackgroundJobStatusIdUnauthorizedError";
  }
}

/** @internal */
export const GetBackgroundJobStatusBackgroundJobStatusIdInternalServerError$inboundSchema:
  z.ZodType<
    GetBackgroundJobStatusBackgroundJobStatusIdInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetBackgroundJobStatusBackgroundJobStatusIdInternalServerError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export const GetBackgroundJobStatusBackgroundJobStatusIdForbiddenError$inboundSchema:
  z.ZodType<
    GetBackgroundJobStatusBackgroundJobStatusIdForbiddenError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetBackgroundJobStatusBackgroundJobStatusIdForbiddenError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetBackgroundJobStatusBackgroundJobStatusIdUnauthorizedError$inboundSchema:
  z.ZodType<
    GetBackgroundJobStatusBackgroundJobStatusIdUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetBackgroundJobStatusBackgroundJobStatusIdUnauthorizedError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });
