/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type GetFoldersInternalServerErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class GetFoldersInternalServerError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetFoldersInternalServerErrorData;

  constructor(
    err: GetFoldersInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetFoldersInternalServerError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type GetFoldersUnauthorizedErrorData = {
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class GetFoldersUnauthorizedError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetFoldersUnauthorizedErrorData;

  constructor(
    err: GetFoldersUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetFoldersUnauthorizedError";
  }
}

/**
 * Bad request
 */
export type GetFoldersBadRequestErrorData = {
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;
};

/**
 * Bad request
 */
export class GetFoldersBadRequestError extends WistiaError {
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetFoldersBadRequestErrorData;

  constructor(
    err: GetFoldersBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetFoldersBadRequestError";
  }
}

/** @internal */
export const GetFoldersInternalServerError$inboundSchema: z.ZodType<
  GetFoldersInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetFoldersInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetFoldersUnauthorizedError$inboundSchema: z.ZodType<
  GetFoldersUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetFoldersUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetFoldersBadRequestError$inboundSchema: z.ZodType<
  GetFoldersBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetFoldersBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
