/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type GetLiveStreamEventsIdInternalServerErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class GetLiveStreamEventsIdInternalServerError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetLiveStreamEventsIdInternalServerErrorData;

  constructor(
    err: GetLiveStreamEventsIdInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetLiveStreamEventsIdInternalServerError";
  }
}

/**
 * Live streaming feature not available
 */
export type GetLiveStreamEventsIdForbiddenErrorData = {
  error?: string | undefined;
};

/**
 * Live streaming feature not available
 */
export class GetLiveStreamEventsIdForbiddenError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetLiveStreamEventsIdForbiddenErrorData;

  constructor(
    err: GetLiveStreamEventsIdForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetLiveStreamEventsIdForbiddenError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type GetLiveStreamEventsIdUnauthorizedErrorData = {
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class GetLiveStreamEventsIdUnauthorizedError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetLiveStreamEventsIdUnauthorizedErrorData;

  constructor(
    err: GetLiveStreamEventsIdUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetLiveStreamEventsIdUnauthorizedError";
  }
}

/** @internal */
export const GetLiveStreamEventsIdInternalServerError$inboundSchema: z.ZodType<
  GetLiveStreamEventsIdInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetLiveStreamEventsIdInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetLiveStreamEventsIdForbiddenError$inboundSchema: z.ZodType<
  GetLiveStreamEventsIdForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetLiveStreamEventsIdForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetLiveStreamEventsIdUnauthorizedError$inboundSchema: z.ZodType<
  GetLiveStreamEventsIdUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetLiveStreamEventsIdUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
