/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type GetLiveStreamEventsInternalServerErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class GetLiveStreamEventsInternalServerError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetLiveStreamEventsInternalServerErrorData;

  constructor(
    err: GetLiveStreamEventsInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetLiveStreamEventsInternalServerError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type GetLiveStreamEventsUnauthorizedErrorData = {
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class GetLiveStreamEventsUnauthorizedError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetLiveStreamEventsUnauthorizedErrorData;

  constructor(
    err: GetLiveStreamEventsUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetLiveStreamEventsUnauthorizedError";
  }
}

/** @internal */
export const GetLiveStreamEventsInternalServerError$inboundSchema: z.ZodType<
  GetLiveStreamEventsInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetLiveStreamEventsInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetLiveStreamEventsUnauthorizedError$inboundSchema: z.ZodType<
  GetLiveStreamEventsUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetLiveStreamEventsUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
