/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type GetMediasMediaHashedIdStatsInternalServerErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class GetMediasMediaHashedIdStatsInternalServerError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetMediasMediaHashedIdStatsInternalServerErrorData;

  constructor(
    err: GetMediasMediaHashedIdStatsInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetMediasMediaHashedIdStatsInternalServerError";
  }
}

/**
 * Resource not found
 */
export type GetMediasMediaHashedIdStatsNotFoundErrorData = {
  error?: string | undefined;
};

/**
 * Resource not found
 */
export class GetMediasMediaHashedIdStatsNotFoundError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetMediasMediaHashedIdStatsNotFoundErrorData;

  constructor(
    err: GetMediasMediaHashedIdStatsNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetMediasMediaHashedIdStatsNotFoundError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type GetMediasMediaHashedIdStatsUnauthorizedErrorData = {
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class GetMediasMediaHashedIdStatsUnauthorizedError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetMediasMediaHashedIdStatsUnauthorizedErrorData;

  constructor(
    err: GetMediasMediaHashedIdStatsUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetMediasMediaHashedIdStatsUnauthorizedError";
  }
}

/**
 * Bad request
 */
export type GetMediasMediaHashedIdStatsBadRequestErrorData = {
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;
};

/**
 * Bad request
 */
export class GetMediasMediaHashedIdStatsBadRequestError extends WistiaError {
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetMediasMediaHashedIdStatsBadRequestErrorData;

  constructor(
    err: GetMediasMediaHashedIdStatsBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetMediasMediaHashedIdStatsBadRequestError";
  }
}

/** @internal */
export const GetMediasMediaHashedIdStatsInternalServerError$inboundSchema:
  z.ZodType<
    GetMediasMediaHashedIdStatsInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetMediasMediaHashedIdStatsInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type GetMediasMediaHashedIdStatsInternalServerError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const GetMediasMediaHashedIdStatsInternalServerError$outboundSchema:
  z.ZodType<
    GetMediasMediaHashedIdStatsInternalServerError$Outbound,
    z.ZodTypeDef,
    GetMediasMediaHashedIdStatsInternalServerError
  > = z.instanceof(GetMediasMediaHashedIdStatsInternalServerError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetMediasMediaHashedIdStatsInternalServerError$ {
  /** @deprecated use `GetMediasMediaHashedIdStatsInternalServerError$inboundSchema` instead. */
  export const inboundSchema =
    GetMediasMediaHashedIdStatsInternalServerError$inboundSchema;
  /** @deprecated use `GetMediasMediaHashedIdStatsInternalServerError$outboundSchema` instead. */
  export const outboundSchema =
    GetMediasMediaHashedIdStatsInternalServerError$outboundSchema;
  /** @deprecated use `GetMediasMediaHashedIdStatsInternalServerError$Outbound` instead. */
  export type Outbound =
    GetMediasMediaHashedIdStatsInternalServerError$Outbound;
}

/** @internal */
export const GetMediasMediaHashedIdStatsNotFoundError$inboundSchema: z.ZodType<
  GetMediasMediaHashedIdStatsNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetMediasMediaHashedIdStatsNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetMediasMediaHashedIdStatsNotFoundError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const GetMediasMediaHashedIdStatsNotFoundError$outboundSchema: z.ZodType<
  GetMediasMediaHashedIdStatsNotFoundError$Outbound,
  z.ZodTypeDef,
  GetMediasMediaHashedIdStatsNotFoundError
> = z.instanceof(GetMediasMediaHashedIdStatsNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetMediasMediaHashedIdStatsNotFoundError$ {
  /** @deprecated use `GetMediasMediaHashedIdStatsNotFoundError$inboundSchema` instead. */
  export const inboundSchema =
    GetMediasMediaHashedIdStatsNotFoundError$inboundSchema;
  /** @deprecated use `GetMediasMediaHashedIdStatsNotFoundError$outboundSchema` instead. */
  export const outboundSchema =
    GetMediasMediaHashedIdStatsNotFoundError$outboundSchema;
  /** @deprecated use `GetMediasMediaHashedIdStatsNotFoundError$Outbound` instead. */
  export type Outbound = GetMediasMediaHashedIdStatsNotFoundError$Outbound;
}

/** @internal */
export const GetMediasMediaHashedIdStatsUnauthorizedError$inboundSchema:
  z.ZodType<
    GetMediasMediaHashedIdStatsUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetMediasMediaHashedIdStatsUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type GetMediasMediaHashedIdStatsUnauthorizedError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const GetMediasMediaHashedIdStatsUnauthorizedError$outboundSchema:
  z.ZodType<
    GetMediasMediaHashedIdStatsUnauthorizedError$Outbound,
    z.ZodTypeDef,
    GetMediasMediaHashedIdStatsUnauthorizedError
  > = z.instanceof(GetMediasMediaHashedIdStatsUnauthorizedError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetMediasMediaHashedIdStatsUnauthorizedError$ {
  /** @deprecated use `GetMediasMediaHashedIdStatsUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema =
    GetMediasMediaHashedIdStatsUnauthorizedError$inboundSchema;
  /** @deprecated use `GetMediasMediaHashedIdStatsUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    GetMediasMediaHashedIdStatsUnauthorizedError$outboundSchema;
  /** @deprecated use `GetMediasMediaHashedIdStatsUnauthorizedError$Outbound` instead. */
  export type Outbound = GetMediasMediaHashedIdStatsUnauthorizedError$Outbound;
}

/** @internal */
export const GetMediasMediaHashedIdStatsBadRequestError$inboundSchema:
  z.ZodType<GetMediasMediaHashedIdStatsBadRequestError, z.ZodTypeDef, unknown> =
    z.object({
      error: z.string().optional(),
      request$: z.instanceof(Request),
      response$: z.instanceof(Response),
      body$: z.string(),
    })
      .transform((v) => {
        return new GetMediasMediaHashedIdStatsBadRequestError(v, {
          request: v.request$,
          response: v.response$,
          body: v.body$,
        });
      });

/** @internal */
export type GetMediasMediaHashedIdStatsBadRequestError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const GetMediasMediaHashedIdStatsBadRequestError$outboundSchema:
  z.ZodType<
    GetMediasMediaHashedIdStatsBadRequestError$Outbound,
    z.ZodTypeDef,
    GetMediasMediaHashedIdStatsBadRequestError
  > = z.instanceof(GetMediasMediaHashedIdStatsBadRequestError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetMediasMediaHashedIdStatsBadRequestError$ {
  /** @deprecated use `GetMediasMediaHashedIdStatsBadRequestError$inboundSchema` instead. */
  export const inboundSchema =
    GetMediasMediaHashedIdStatsBadRequestError$inboundSchema;
  /** @deprecated use `GetMediasMediaHashedIdStatsBadRequestError$outboundSchema` instead. */
  export const outboundSchema =
    GetMediasMediaHashedIdStatsBadRequestError$outboundSchema;
  /** @deprecated use `GetMediasMediaHashedIdStatsBadRequestError$Outbound` instead. */
  export type Outbound = GetMediasMediaHashedIdStatsBadRequestError$Outbound;
}
