/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { WistiaError } from "./wistiaerror.js";

/**
 * Project or subfolder not found
 */
export type GetProjectsProjectIdSubfoldersSubfolderIdNotFoundErrorData = {
  error?: string | undefined;
};

/**
 * Project or subfolder not found
 */
export class GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetProjectsProjectIdSubfoldersSubfolderIdNotFoundErrorData;

  constructor(
    err: GetProjectsProjectIdSubfoldersSubfolderIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError";
  }
}

/** @internal */
export const GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError$inboundSchema:
  z.ZodType<
    GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export type GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError$outboundSchema:
  z.ZodType<
    GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError$Outbound,
    z.ZodTypeDef,
    GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError
  > = z.instanceof(GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError$ {
  /** @deprecated use `GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError$inboundSchema` instead. */
  export const inboundSchema =
    GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError$inboundSchema;
  /** @deprecated use `GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError$outboundSchema` instead. */
  export const outboundSchema =
    GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError$outboundSchema;
  /** @deprecated use `GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError$Outbound` instead. */
  export type Outbound =
    GetProjectsProjectIdSubfoldersSubfolderIdNotFoundError$Outbound;
}
