/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type GetStatsEventsEventKeyInternalServerErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class GetStatsEventsEventKeyInternalServerError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetStatsEventsEventKeyInternalServerErrorData;

  constructor(
    err: GetStatsEventsEventKeyInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetStatsEventsEventKeyInternalServerError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type GetStatsEventsEventKeyUnauthorizedErrorData = {
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class GetStatsEventsEventKeyUnauthorizedError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetStatsEventsEventKeyUnauthorizedErrorData;

  constructor(
    err: GetStatsEventsEventKeyUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetStatsEventsEventKeyUnauthorizedError";
  }
}

/** @internal */
export const GetStatsEventsEventKeyInternalServerError$inboundSchema: z.ZodType<
  GetStatsEventsEventKeyInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetStatsEventsEventKeyInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetStatsEventsEventKeyUnauthorizedError$inboundSchema: z.ZodType<
  GetStatsEventsEventKeyUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetStatsEventsEventKeyUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
