/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type GetWebinarsWebinarIdRegistrationsInternalServerErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class GetWebinarsWebinarIdRegistrationsInternalServerError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetWebinarsWebinarIdRegistrationsInternalServerErrorData;

  constructor(
    err: GetWebinarsWebinarIdRegistrationsInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetWebinarsWebinarIdRegistrationsInternalServerError";
  }
}

/**
 * Resource not found
 */
export type GetWebinarsWebinarIdRegistrationsNotFoundErrorData = {
  error?: string | undefined;
};

/**
 * Resource not found
 */
export class GetWebinarsWebinarIdRegistrationsNotFoundError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetWebinarsWebinarIdRegistrationsNotFoundErrorData;

  constructor(
    err: GetWebinarsWebinarIdRegistrationsNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetWebinarsWebinarIdRegistrationsNotFoundError";
  }
}

/**
 * Webinar feature not available
 */
export type GetWebinarsWebinarIdRegistrationsForbiddenErrorData = {
  error?: string | undefined;
};

/**
 * Webinar feature not available
 */
export class GetWebinarsWebinarIdRegistrationsForbiddenError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetWebinarsWebinarIdRegistrationsForbiddenErrorData;

  constructor(
    err: GetWebinarsWebinarIdRegistrationsForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetWebinarsWebinarIdRegistrationsForbiddenError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type GetWebinarsWebinarIdRegistrationsUnauthorizedErrorData = {
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class GetWebinarsWebinarIdRegistrationsUnauthorizedError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: GetWebinarsWebinarIdRegistrationsUnauthorizedErrorData;

  constructor(
    err: GetWebinarsWebinarIdRegistrationsUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "GetWebinarsWebinarIdRegistrationsUnauthorizedError";
  }
}

/** @internal */
export const GetWebinarsWebinarIdRegistrationsInternalServerError$inboundSchema:
  z.ZodType<
    GetWebinarsWebinarIdRegistrationsInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetWebinarsWebinarIdRegistrationsInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetWebinarsWebinarIdRegistrationsNotFoundError$inboundSchema:
  z.ZodType<
    GetWebinarsWebinarIdRegistrationsNotFoundError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetWebinarsWebinarIdRegistrationsNotFoundError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetWebinarsWebinarIdRegistrationsForbiddenError$inboundSchema:
  z.ZodType<
    GetWebinarsWebinarIdRegistrationsForbiddenError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetWebinarsWebinarIdRegistrationsForbiddenError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetWebinarsWebinarIdRegistrationsUnauthorizedError$inboundSchema:
  z.ZodType<
    GetWebinarsWebinarIdRegistrationsUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new GetWebinarsWebinarIdRegistrationsUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });
