/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type PostContactsInternalServerErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class PostContactsInternalServerError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostContactsInternalServerErrorData;

  constructor(
    err: PostContactsInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PostContactsInternalServerError";
  }
}

/**
 * Unprocessable entity, the request parameters were invalid.
 */
export type PostContactsUnprocessableEntityErrorData = {
  /**
   * A single error message describing what went wrong.
   */
  error?: string | undefined;
  /**
   * Array of error messages describing what went wrong.
   */
  errors?: Array<string> | undefined;
};

/**
 * Unprocessable entity, the request parameters were invalid.
 */
export class PostContactsUnprocessableEntityError extends WistiaError {
  /**
   * A single error message describing what went wrong.
   */
  error?: string | undefined;
  /**
   * Array of error messages describing what went wrong.
   */
  errors?: Array<string> | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostContactsUnprocessableEntityErrorData;

  constructor(
    err: PostContactsUnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.errors != null) this.errors = err.errors;

    this.name = "PostContactsUnprocessableEntityError";
  }
}

/**
 * Forbidden, token is valid but account does not have access to feature
 */
export type PostContactsForbiddenErrorData = {
  error?: string | undefined;
};

/**
 * Forbidden, token is valid but account does not have access to feature
 */
export class PostContactsForbiddenError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostContactsForbiddenErrorData;

  constructor(
    err: PostContactsForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PostContactsForbiddenError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type PostContactsUnauthorizedErrorData = {
  /**
   * A machine-readable identifier for the specific authorization failure.
   */
  code?: operations.PostContactsCode | undefined;
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class PostContactsUnauthorizedError extends WistiaError {
  /**
   * A machine-readable identifier for the specific authorization failure.
   */
  code?: operations.PostContactsCode | undefined;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostContactsUnauthorizedErrorData;

  constructor(
    err: PostContactsUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.error != null) this.error = err.error;

    this.name = "PostContactsUnauthorizedError";
  }
}

/**
 * Bad request
 */
export type PostContactsBadRequestErrorData = {
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;
  /**
   * Array of error messages detailing the reasons for the bad request.
   */
  errors?: Array<string> | undefined;
};

/**
 * Bad request
 */
export class PostContactsBadRequestError extends WistiaError {
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;
  /**
   * Array of error messages detailing the reasons for the bad request.
   */
  errors?: Array<string> | undefined;

  /** The original data that was passed to this error instance. */
  data$: PostContactsBadRequestErrorData;

  constructor(
    err: PostContactsBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.errors != null) this.errors = err.errors;

    this.name = "PostContactsBadRequestError";
  }
}

/** @internal */
export const PostContactsInternalServerError$inboundSchema: z.ZodType<
  PostContactsInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostContactsInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostContactsUnprocessableEntityError$inboundSchema: z.ZodType<
  PostContactsUnprocessableEntityError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  errors: z.array(z.string()).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostContactsUnprocessableEntityError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostContactsForbiddenError$inboundSchema: z.ZodType<
  PostContactsForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostContactsForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostContactsUnauthorizedError$inboundSchema: z.ZodType<
  PostContactsUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: operations.PostContactsCode$inboundSchema.optional(),
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostContactsUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostContactsBadRequestError$inboundSchema: z.ZodType<
  PostContactsBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  errors: z.array(z.string()).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostContactsBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
