/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import * as operations from "../operations/index.js";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type PutMediasMediaIdCustomizationsSharingInternalServerErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class PutMediasMediaIdCustomizationsSharingInternalServerError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PutMediasMediaIdCustomizationsSharingInternalServerErrorData;

  constructor(
    err: PutMediasMediaIdCustomizationsSharingInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PutMediasMediaIdCustomizationsSharingInternalServerError";
  }
}

/**
 * Resource not found
 */
export type PutMediasMediaIdCustomizationsSharingNotFoundErrorData = {
  error?: string | undefined;
};

/**
 * Resource not found
 */
export class PutMediasMediaIdCustomizationsSharingNotFoundError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PutMediasMediaIdCustomizationsSharingNotFoundErrorData;

  constructor(
    err: PutMediasMediaIdCustomizationsSharingNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PutMediasMediaIdCustomizationsSharingNotFoundError";
  }
}

/**
 * Forbidden, token is valid but account does not have access to feature
 */
export type PutMediasMediaIdCustomizationsSharingForbiddenErrorData = {
  error?: string | undefined;
};

/**
 * Forbidden, token is valid but account does not have access to feature
 */
export class PutMediasMediaIdCustomizationsSharingForbiddenError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PutMediasMediaIdCustomizationsSharingForbiddenErrorData;

  constructor(
    err: PutMediasMediaIdCustomizationsSharingForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PutMediasMediaIdCustomizationsSharingForbiddenError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type PutMediasMediaIdCustomizationsSharingUnauthorizedErrorData = {
  /**
   * A machine-readable identifier for the specific authorization failure.
   */
  code?: operations.PutMediasMediaIdCustomizationsSharingCode | undefined;
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class PutMediasMediaIdCustomizationsSharingUnauthorizedError
  extends WistiaError
{
  /**
   * A machine-readable identifier for the specific authorization failure.
   */
  code?: operations.PutMediasMediaIdCustomizationsSharingCode | undefined;
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PutMediasMediaIdCustomizationsSharingUnauthorizedErrorData;

  constructor(
    err: PutMediasMediaIdCustomizationsSharingUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.code != null) this.code = err.code;
    if (err.error != null) this.error = err.error;

    this.name = "PutMediasMediaIdCustomizationsSharingUnauthorizedError";
  }
}

/**
 * Bad request
 */
export type PutMediasMediaIdCustomizationsSharingBadRequestErrorData = {
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;
  /**
   * Array of error messages detailing the reasons for the bad request.
   */
  errors?: Array<string> | undefined;
};

/**
 * Bad request
 */
export class PutMediasMediaIdCustomizationsSharingBadRequestError
  extends WistiaError
{
  /**
   * Error message detailing the reason for the bad request.
   */
  error?: string | undefined;
  /**
   * Array of error messages detailing the reasons for the bad request.
   */
  errors?: Array<string> | undefined;

  /** The original data that was passed to this error instance. */
  data$: PutMediasMediaIdCustomizationsSharingBadRequestErrorData;

  constructor(
    err: PutMediasMediaIdCustomizationsSharingBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;
    if (err.errors != null) this.errors = err.errors;

    this.name = "PutMediasMediaIdCustomizationsSharingBadRequestError";
  }
}

/** @internal */
export const PutMediasMediaIdCustomizationsSharingInternalServerError$inboundSchema:
  z.ZodType<
    PutMediasMediaIdCustomizationsSharingInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PutMediasMediaIdCustomizationsSharingInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const PutMediasMediaIdCustomizationsSharingNotFoundError$inboundSchema:
  z.ZodType<
    PutMediasMediaIdCustomizationsSharingNotFoundError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PutMediasMediaIdCustomizationsSharingNotFoundError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const PutMediasMediaIdCustomizationsSharingForbiddenError$inboundSchema:
  z.ZodType<
    PutMediasMediaIdCustomizationsSharingForbiddenError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PutMediasMediaIdCustomizationsSharingForbiddenError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const PutMediasMediaIdCustomizationsSharingUnauthorizedError$inboundSchema:
  z.ZodType<
    PutMediasMediaIdCustomizationsSharingUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: operations.PutMediasMediaIdCustomizationsSharingCode$inboundSchema
      .optional(),
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PutMediasMediaIdCustomizationsSharingUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const PutMediasMediaIdCustomizationsSharingBadRequestError$inboundSchema:
  z.ZodType<
    PutMediasMediaIdCustomizationsSharingBadRequestError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    errors: z.array(z.string()).optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PutMediasMediaIdCustomizationsSharingBadRequestError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });
