/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerErrorData =
  {
    error?: string | undefined;
  };

/**
 * Internal server error
 */
export class PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerErrorData;

  constructor(
    err: PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedErrorData = {
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedErrorData;

  constructor(
    err: PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError";
  }
}

/** @internal */
export const PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError$inboundSchema:
  z.ZodType<
    PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export type PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError$Outbound =
  {
    error?: string | undefined;
  };

/** @internal */
export const PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError$outboundSchema:
  z.ZodType<
    PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError$Outbound,
    z.ZodTypeDef,
    PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError
  > = z.instanceof(
    PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError,
  )
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError$ {
  /** @deprecated use `PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError$inboundSchema` instead. */
  export const inboundSchema =
    PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError$inboundSchema;
  /** @deprecated use `PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError$outboundSchema` instead. */
  export const outboundSchema =
    PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError$outboundSchema;
  /** @deprecated use `PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError$Outbound` instead. */
  export type Outbound =
    PutMediasMediaHashedIdCaptionsLanguageCodeInternalServerError$Outbound;
}

/** @internal */
export const PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError$inboundSchema:
  z.ZodType<
    PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError(
        v,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export type PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError$Outbound =
  {
    error?: string | undefined;
  };

/** @internal */
export const PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError$outboundSchema:
  z.ZodType<
    PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError$Outbound,
    z.ZodTypeDef,
    PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError
  > = z.instanceof(PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError)
    .transform(v => v.data$)
    .pipe(z.object({
      error: z.string().optional(),
    }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError$ {
  /** @deprecated use `PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema =
    PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError$inboundSchema;
  /** @deprecated use `PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema =
    PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError$outboundSchema;
  /** @deprecated use `PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError$Outbound` instead. */
  export type Outbound =
    PutMediasMediaHashedIdCaptionsLanguageCodeUnauthorizedError$Outbound;
}
