/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { WistiaError } from "./wistiaerror.js";

/**
 * Internal server error
 */
export type PutMediasMediaIdCustomizationsInternalServerErrorData = {
  error?: string | undefined;
};

/**
 * Internal server error
 */
export class PutMediasMediaIdCustomizationsInternalServerError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PutMediasMediaIdCustomizationsInternalServerErrorData;

  constructor(
    err: PutMediasMediaIdCustomizationsInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PutMediasMediaIdCustomizationsInternalServerError";
  }
}

/**
 * Resource not found
 */
export type PutMediasMediaIdCustomizationsNotFoundErrorData = {
  error?: string | undefined;
};

/**
 * Resource not found
 */
export class PutMediasMediaIdCustomizationsNotFoundError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PutMediasMediaIdCustomizationsNotFoundErrorData;

  constructor(
    err: PutMediasMediaIdCustomizationsNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PutMediasMediaIdCustomizationsNotFoundError";
  }
}

/**
 * Unauthorized, invalid or missing token
 */
export type PutMediasMediaIdCustomizationsUnauthorizedErrorData = {
  error?: string | undefined;
};

/**
 * Unauthorized, invalid or missing token
 */
export class PutMediasMediaIdCustomizationsUnauthorizedError
  extends WistiaError
{
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PutMediasMediaIdCustomizationsUnauthorizedErrorData;

  constructor(
    err: PutMediasMediaIdCustomizationsUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PutMediasMediaIdCustomizationsUnauthorizedError";
  }
}

/** @internal */
export const PutMediasMediaIdCustomizationsInternalServerError$inboundSchema:
  z.ZodType<
    PutMediasMediaIdCustomizationsInternalServerError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PutMediasMediaIdCustomizationsInternalServerError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const PutMediasMediaIdCustomizationsNotFoundError$inboundSchema:
  z.ZodType<
    PutMediasMediaIdCustomizationsNotFoundError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PutMediasMediaIdCustomizationsNotFoundError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const PutMediasMediaIdCustomizationsUnauthorizedError$inboundSchema:
  z.ZodType<
    PutMediasMediaIdCustomizationsUnauthorizedError,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.string().optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      return new PutMediasMediaIdCustomizationsUnauthorizedError(v, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });
