/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { WistiaError } from "./wistiaerror.js";

/**
 * Invalid request.
 */
export type PutMediasMoveBadRequestErrorData = {
  error?: string | undefined;
};

/**
 * Invalid request.
 */
export class PutMediasMoveBadRequestError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PutMediasMoveBadRequestErrorData;

  constructor(
    err: PutMediasMoveBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PutMediasMoveBadRequestError";
  }
}

/** @internal */
export const PutMediasMoveBadRequestError$inboundSchema: z.ZodType<
  PutMediasMoveBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PutMediasMoveBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PutMediasMoveBadRequestError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const PutMediasMoveBadRequestError$outboundSchema: z.ZodType<
  PutMediasMoveBadRequestError$Outbound,
  z.ZodTypeDef,
  PutMediasMoveBadRequestError
> = z.instanceof(PutMediasMoveBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutMediasMoveBadRequestError$ {
  /** @deprecated use `PutMediasMoveBadRequestError$inboundSchema` instead. */
  export const inboundSchema = PutMediasMoveBadRequestError$inboundSchema;
  /** @deprecated use `PutMediasMoveBadRequestError$outboundSchema` instead. */
  export const outboundSchema = PutMediasMoveBadRequestError$outboundSchema;
  /** @deprecated use `PutMediasMoveBadRequestError$Outbound` instead. */
  export type Outbound = PutMediasMoveBadRequestError$Outbound;
}
