/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { WistiaError } from "./wistiaerror.js";

/**
 * Unprocessable entity, e.g. too many media requested.
 */
export type PutMediasArchiveUnprocessableEntityErrorData = {
  error?: string | undefined;
};

/**
 * Unprocessable entity, e.g. too many media requested.
 */
export class PutMediasArchiveUnprocessableEntityError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PutMediasArchiveUnprocessableEntityErrorData;

  constructor(
    err: PutMediasArchiveUnprocessableEntityErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PutMediasArchiveUnprocessableEntityError";
  }
}

/**
 * Forbidden, e.g. account does not have access to archiving.
 */
export type PutMediasArchiveForbiddenErrorData = {
  error?: string | undefined;
};

/**
 * Forbidden, e.g. account does not have access to archiving.
 */
export class PutMediasArchiveForbiddenError extends WistiaError {
  error?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: PutMediasArchiveForbiddenErrorData;

  constructor(
    err: PutMediasArchiveForbiddenErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.error != null) this.error = err.error;

    this.name = "PutMediasArchiveForbiddenError";
  }
}

/** @internal */
export const PutMediasArchiveUnprocessableEntityError$inboundSchema: z.ZodType<
  PutMediasArchiveUnprocessableEntityError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PutMediasArchiveUnprocessableEntityError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PutMediasArchiveUnprocessableEntityError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const PutMediasArchiveUnprocessableEntityError$outboundSchema: z.ZodType<
  PutMediasArchiveUnprocessableEntityError$Outbound,
  z.ZodTypeDef,
  PutMediasArchiveUnprocessableEntityError
> = z.instanceof(PutMediasArchiveUnprocessableEntityError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutMediasArchiveUnprocessableEntityError$ {
  /** @deprecated use `PutMediasArchiveUnprocessableEntityError$inboundSchema` instead. */
  export const inboundSchema =
    PutMediasArchiveUnprocessableEntityError$inboundSchema;
  /** @deprecated use `PutMediasArchiveUnprocessableEntityError$outboundSchema` instead. */
  export const outboundSchema =
    PutMediasArchiveUnprocessableEntityError$outboundSchema;
  /** @deprecated use `PutMediasArchiveUnprocessableEntityError$Outbound` instead. */
  export type Outbound = PutMediasArchiveUnprocessableEntityError$Outbound;
}

/** @internal */
export const PutMediasArchiveForbiddenError$inboundSchema: z.ZodType<
  PutMediasArchiveForbiddenError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PutMediasArchiveForbiddenError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type PutMediasArchiveForbiddenError$Outbound = {
  error?: string | undefined;
};

/** @internal */
export const PutMediasArchiveForbiddenError$outboundSchema: z.ZodType<
  PutMediasArchiveForbiddenError$Outbound,
  z.ZodTypeDef,
  PutMediasArchiveForbiddenError
> = z.instanceof(PutMediasArchiveForbiddenError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string().optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutMediasArchiveForbiddenError$ {
  /** @deprecated use `PutMediasArchiveForbiddenError$inboundSchema` instead. */
  export const inboundSchema = PutMediasArchiveForbiddenError$inboundSchema;
  /** @deprecated use `PutMediasArchiveForbiddenError$outboundSchema` instead. */
  export const outboundSchema = PutMediasArchiveForbiddenError$outboundSchema;
  /** @deprecated use `PutMediasArchiveForbiddenError$Outbound` instead. */
  export type Outbound = PutMediasArchiveForbiddenError$Outbound;
}
