/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountGetAccountDetails } from "../funcs/accountGetAccountDetails.js";
import { accountGetTokenDetails } from "../funcs/accountGetTokenDetails.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Account extends ClientSDK {
  /**
   * Get Current Account
   *
   * @remarks
   * Retrieves a summary of the Wistia account including account name, description, URL and counts of records.
   *
   * ## Requires api token with one of the following permissions
   * ```
   * (any scope allowed)
   * ```
   */
  async getAccountDetails(
    options?: RequestOptions,
  ): Promise<operations.GetAccountDetailsResponse> {
    return unwrapAsync(accountGetAccountDetails(
      this,
      options,
    ));
  }

  /**
   * Get Current Token
   *
   * @remarks
   * Retrieves a summary of the token used to make the API request. This endpoint can primarily be used to
   * debug permission issues with the API.
   */
  async getTokenDetails(
    options?: RequestOptions,
  ): Promise<operations.GetTokenDetailsResponse> {
    return unwrapAsync(accountGetTokenDetails(
      this,
      options,
    ));
  }
}
