/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { backgroundJobStatusGetBackgroundJobStatusBackgroundJobStatusId } from "../funcs/backgroundJobStatusGetBackgroundJobStatusBackgroundJobStatusId.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class BackgroundJobStatus extends ClientSDK {
  /**
   * Show Background Job Status
   *
   * @remarks
   * Retrieves the status of a background job.
   *
   * ## Requires api token with one of the following permissions
   * ```
   * Read all data
   * ```
   */
  async getBackgroundJobStatusBackgroundJobStatusId(
    request: operations.GetBackgroundJobStatusBackgroundJobStatusIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetBackgroundJobStatusBackgroundJobStatusIdResponse> {
    return unwrapAsync(
      backgroundJobStatusGetBackgroundJobStatusBackgroundJobStatusId(
        this,
        request,
        options,
      ),
    );
  }
}
