/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { folderSharingsCreate } from "../funcs/folderSharingsCreate.js";
import { folderSharingsDelete } from "../funcs/folderSharingsDelete.js";
import { folderSharingsGet } from "../funcs/folderSharingsGet.js";
import { folderSharingsList } from "../funcs/folderSharingsList.js";
import { folderSharingsUpdate } from "../funcs/folderSharingsUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class FolderSharings extends ClientSDK {
  /**
   * List Folder Sharings
   *
   * @remarks
   * Lists the sharings of contacts and contact groups on a folder.
   *
   * ## Requires api token with one of the following permissions
   * ```
   * Read all data
   * ```
   *
   * Tokens with the "Act with a team member's permissions" permission
   * (`all:delegate_to_contact_permissions` scope) can also be used. Requests
   * made with such a token are authorized using the permissions of the
   * contact assigned to the token.
   *
   * An [expiring access token](https://docs.wistia.com/reference/post_expiring-token)
   * created with the `all:delegate_to_contact_permissions` scope and an
   * authorization naming this folder (any permission) can also be used; it
   * lists the folder's sharings.
   */
  async list(
    request: operations.GetFoldersFolderIdSharingsRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.GetFoldersFolderIdSharingsResponse>> {
    return unwrapAsync(folderSharingsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Folder Sharing
   *
   * @remarks
   * Creates a new sharing object for a folder by specifying the email of the person to share with and other optional parameters.
   *
   * ## Requires api token with one of the following permissions
   * ```
   * Read, update & delete anything
   * ```
   *
   * Tokens with the "Act with a team member's permissions" permission
   * (`all:delegate_to_contact_permissions` scope) can also be used. Requests
   * made with such a token are authorized using the permissions of the
   * contact assigned to the token.
   *
   * An [expiring access token](https://docs.wistia.com/reference/post_expiring-token)
   * created with the `all:delegate_to_contact_permissions` scope and an
   * authorization granting the `share` permission on this folder can also
   * be used.
   */
  async create(
    request: operations.PostFoldersFolderIdSharingsRequest,
    options?: RequestOptions,
  ): Promise<operations.PostFoldersFolderIdSharingsResponse> {
    return unwrapAsync(folderSharingsCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Show Folder Sharing
   *
   * @remarks
   * Retrieves the details of a specific sharing object for a given folder.
   *
   * ## Requires api token with one of the following permissions
   * ```
   * Read all data
   * ```
   *
   * Tokens with the "Act with a team member's permissions" permission
   * (`all:delegate_to_contact_permissions` scope) can also be used. Requests
   * made with such a token are authorized using the permissions of the
   * contact assigned to the token.
   *
   * An [expiring access token](https://docs.wistia.com/reference/post_expiring-token)
   * created with the `all:delegate_to_contact_permissions` scope and an
   * authorization naming this folder (any permission) can also be used.
   */
  async get(
    request: operations.GetFoldersFolderIdSharingsSharingIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetFoldersFolderIdSharingsSharingIdResponse> {
    return unwrapAsync(folderSharingsGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update Folder Sharing
   *
   * @remarks
   * Updates a sharing on a folder.
   *
   * ## Requires api token with one of the following permissions
   * ```
   * Read, update & delete anything
   * ```
   *
   * Tokens with the "Act with a team member's permissions" permission
   * (`all:delegate_to_contact_permissions` scope) can also be used. Requests
   * made with such a token are authorized using the permissions of the
   * contact assigned to the token.
   *
   * An [expiring access token](https://docs.wistia.com/reference/post_expiring-token)
   * created with the `all:delegate_to_contact_permissions` scope and an
   * authorization granting the `update` permission on this folder can also
   * be used.
   */
  async update(
    request: operations.PutFoldersFolderIdSharingsSharingIdRequest,
    options?: RequestOptions,
  ): Promise<operations.PutFoldersFolderIdSharingsSharingIdResponse> {
    return unwrapAsync(folderSharingsUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete Folder Sharing
   *
   * @remarks
   * Deletes a sharing on a folder.
   *
   * ## Requires api token with one of the following permissions
   * ```
   * Read, update & delete anything
   * ```
   *
   * Tokens with the "Act with a team member's permissions" permission
   * (`all:delegate_to_contact_permissions` scope) can also be used. Requests
   * made with such a token are authorized using the permissions of the
   * contact assigned to the token.
   *
   * An [expiring access token](https://docs.wistia.com/reference/post_expiring-token)
   * created with the `all:delegate_to_contact_permissions` scope and an
   * authorization granting the `update` permission on this folder can also
   * be used.
   */
  async delete(
    request: operations.DeleteFoldersFolderIdSharingsSharingIdRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteFoldersFolderIdSharingsSharingIdResponse> {
    return unwrapAsync(folderSharingsDelete(
      this,
      request,
      options,
    ));
  }
}
