/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchSearch } from "../funcs/searchSearch.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Search extends ClientSDK {
  /**
   * Search
   *
   * @remarks
   * Searches across folders, subfolders, medias, channels, channel episodes, and webinars.
   * Also searches through video transcripts, so media results may include transcript matches with
   * timestamps when the query matches spoken content.
   *
   * ## Requires api token with one of the following permissions
   * ```
   * Read all data
   * ```
   */
  async search(
    request: operations.GetSearchRequest,
    options?: RequestOptions,
  ): Promise<operations.GetSearchResponse> {
    return unwrapAsync(searchSearch(
      this,
      request,
      options,
    ));
  }
}
