/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { speakersAssign } from "../funcs/speakersAssign.js";
import { speakersCreate } from "../funcs/speakersCreate.js";
import { speakersList } from "../funcs/speakersList.js";
import { speakersRemove } from "../funcs/speakersRemove.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Speakers extends ClientSDK {
  /**
   * Assign Speaker to Media
   *
   * @remarks
   * Assigns a reusable speaker profile to a media. With `detected_speaker_id`,
   * every turn by that detected speaker is attributed to the profile, and
   * assigning a second detected speaker to the same profile merges them.
   * Without it, the speaker is credited on the media without naming turns.
   *
   * Naming a detected speaker requires the current `speaker_data_version` as
   * `expected_version`, and isn't available while the account has speaker
   * identification turned off.
   *
   * ## Requires api token with one of the following permissions
   * ```
   * Read, update & delete anything
   * ```
   *
   * Tokens with the "Act with a team member's permissions" permission
   * (`all:delegate_to_contact_permissions` scope) can also be used. Requests
   * made with such a token are authorized using the permissions of the
   * contact assigned to the token, who must be able to edit the media's
   * transcript and view the account's speaker profiles.
   */
  async assign(
    request: operations.PostMediasMediaHashedIdSpeakersRequest,
    options?: RequestOptions,
  ): Promise<operations.PostMediasMediaHashedIdSpeakersResponse> {
    return unwrapAsync(speakersAssign(
      this,
      request,
      options,
    ));
  }

  /**
   * Remove Speaker from Media
   *
   * @remarks
   * Removes a speaker assignment from a media. Every turn attributed to the
   * speaker returns to an anonymous detected speaker, which can be named again
   * by assigning it. The speaker's profile stays in the account's speaker
   * library.
   *
   * Pass the media's current `speaker_data_version` as `expected_version` to
   * reject the removal if the speaker data changed since you read it.
   *
   * ## Requires api token with one of the following permissions
   * ```
   * Read, update & delete anything
   * ```
   *
   * Tokens with the "Act with a team member's permissions" permission
   * (`all:delegate_to_contact_permissions` scope) can also be used. Requests
   * made with such a token are authorized using the permissions of the
   * contact assigned to the token, who must be able to edit the media's
   * transcript and view the account's speaker profiles.
   */
  async remove(
    request: operations.DeleteMediasMediaHashedIdSpeakersMediaSpeakerIdRequest,
    options?: RequestOptions,
  ): Promise<
    operations.DeleteMediasMediaHashedIdSpeakersMediaSpeakerIdResponse
  > {
    return unwrapAsync(speakersRemove(
      this,
      request,
      options,
    ));
  }

  /**
   * List Speakers
   *
   * @remarks
   * Lists reusable speaker profiles belonging to the account.
   *
   * ## Requires api token with one of the following permissions
   * ```
   * Read all data
   * ```
   *
   * Tokens with the "Act with a team member's permissions" permission
   * (`all:delegate_to_contact_permissions` scope) can also be used. Requests
   * made with such a token are authorized using the permissions of the
   * contact assigned to the token. View-only contacts cannot list speaker
   * profiles.
   */
  async list(
    request?: operations.GetSpeakersRequest | undefined,
    options?: RequestOptions,
  ): Promise<Array<operations.GetSpeakersResponse>> {
    return unwrapAsync(speakersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Create Speaker
   *
   * @remarks
   * Adds a reusable speaker profile to the account's speaker library. The
   * returned `speaker_profile_id` identifies the profile in speaker filters and
   * assignments.
   *
   * Speaker names are not unique, because two different people can share one.
   * A request whose name matches an existing profile creates a second profile;
   * use the List Speakers endpoint to look for the person first.
   *
   * A new profile isn't assigned to any media.
   *
   * ## Requires api token with one of the following permissions
   * ```
   * All data
   * ```
   *
   * Tokens with the "Act with a team member's permissions" permission
   * (`all:delegate_to_contact_permissions` scope) can also be used. Requests
   * made with such a token are authorized using the permissions of the
   * contact assigned to the token. Only account owners and managers can
   * create speaker profiles.
   */
  async create(
    request: operations.PostSpeakersRequest,
    options?: RequestOptions,
  ): Promise<operations.PostSpeakersResponse> {
    return unwrapAsync(speakersCreate(
      this,
      request,
      options,
    ));
  }
}
