/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statsMediaGetStatsMediasMediaId } from "../funcs/statsMediaGetStatsMediasMediaId.js";
import { statsMediaGetStatsMediasMediaIdByDate } from "../funcs/statsMediaGetStatsMediasMediaIdByDate.js";
import { statsMediaGetStatsMediasMediaIdEngagement } from "../funcs/statsMediaGetStatsMediasMediaIdEngagement.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class StatsMedia extends ClientSDK {
  /**
   * Show Media Stats
   *
   * @remarks
   * Retrieve stats for a video. This endpoint provides statistics for a specific video identified by its media-id.
   *
   * <!--- HIDE-MCP -->
   * ## Requires api token with one of the following permissions
   * ```
   * Read detailed stats
   * ```
   * <!--- /HIDE-MCP -->
   */
  async getStatsMediasMediaId(
    request: operations.GetStatsMediasMediaIdRequest,
    options?: RequestOptions,
  ): Promise<operations.GetStatsMediasMediaIdResponse> {
    return unwrapAsync(statsMediaGetStatsMediasMediaId(
      this,
      request,
      options,
    ));
  }

  /**
   * Show Media Stats by Date
   *
   * @remarks
   * Retrieve stats for a media organized by day, between a start and end date paramater (inclusive). If start and end date are not provided, defaults to yesterday and today.
   *
   * <!--- HIDE-MCP -->
   * ## Requires api token with one of the following permissions
   * ```
   * Read detailed stats
   * ```
   * <!--- /HIDE-MCP -->
   */
  async getStatsMediasMediaIdByDate(
    request: operations.GetStatsMediasMediaIdByDateRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.GetStatsMediasMediaIdByDateResponse>> {
    return unwrapAsync(statsMediaGetStatsMediasMediaIdByDate(
      this,
      request,
      options,
    ));
  }

  /**
   * Show Media Engagement
   *
   * @remarks
   * Retrieve engagement data for a video. This endpoint provides engagement data for a specific video identified by its media-id.
   *
   * <!--- HIDE-MCP -->
   * ## Requires api token with one of the following permissions
   * ```
   * Read detailed stats
   * ```
   * <!--- /HIDE-MCP -->
   */
  async getStatsMediasMediaIdEngagement(
    request: operations.GetStatsMediasMediaIdEngagementRequest,
    options?: RequestOptions,
  ): Promise<operations.GetStatsMediasMediaIdEngagementResponse> {
    return unwrapAsync(statsMediaGetStatsMediasMediaIdEngagement(
      this,
      request,
      options,
    ));
  }
}
