workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Data API:
        inputs:
            - location: ../wistia.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/sheldon-vaughn-test/sandbox/data-api
targets:
    wistia:
        target: typescript
        source: Data API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/sheldon-vaughn-test/sandbox/data-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
