workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Data API:
        inputs:
            - location: https://wistia.github.io/wistia/api/openapi-upload.yaml
            - location: https://wistia.github.io/wistia/api/openapi-2026-03.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/wistia/wistia/data-api-2026-03
    docs:
        inputs:
            - location: https://wistia.github.io/wistia/api/openapi-upload.yaml
            - location: https://wistia.github.io/wistia/api/openapi-2026-03.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
            - location: registry.speakeasyapi.dev/wistia/wistia/data-api-2026-03-typescript-code-samples
        output: .speakeasy/openapi-with-code-samples.yaml
        registry:
            location: registry.speakeasyapi.dev/wistia/wistia/data-api-2026-03-docs
targets:
    wistia:
        target: typescript
        source: Data API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            output: code-samples.yaml
            registry:
                location: registry.speakeasyapi.dev/wistia/wistia/data-api-2026-03-typescript-code-samples
            style: readme
            langOverride: javascript
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
