workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Data API:
        inputs:
            - location: https://wistia.github.io/wistia/api/openapi.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/wistia/wistia/data-api
targets:
    wistia:
        target: typescript
        source: Data API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/wistia/wistia/data-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
