/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

export type DeleteCustomMetadataFieldDefinitionsKeyRequest = {
  /**
   * The field's immutable key
   */
  key: string;
};

/**
 * A machine-readable identifier for the specific authorization failure.
 */
export const DeleteCustomMetadataFieldDefinitionsKeyCode = {
  UnauthorizedCredentials: "unauthorized_credentials",
  AccountInactive: "account_inactive",
  UnauthorizedScope: "unauthorized_scope",
  UnauthorizedParams: "unauthorized_params",
} as const;
/**
 * A machine-readable identifier for the specific authorization failure.
 */
export type DeleteCustomMetadataFieldDefinitionsKeyCode = ClosedEnum<
  typeof DeleteCustomMetadataFieldDefinitionsKeyCode
>;

/** @internal */
export type DeleteCustomMetadataFieldDefinitionsKeyRequest$Outbound = {
  key: string;
};

/** @internal */
export const DeleteCustomMetadataFieldDefinitionsKeyRequest$outboundSchema:
  z.ZodType<
    DeleteCustomMetadataFieldDefinitionsKeyRequest$Outbound,
    z.ZodTypeDef,
    DeleteCustomMetadataFieldDefinitionsKeyRequest
  > = z.object({
    key: z.string(),
  });

export function deleteCustomMetadataFieldDefinitionsKeyRequestToJSON(
  deleteCustomMetadataFieldDefinitionsKeyRequest:
    DeleteCustomMetadataFieldDefinitionsKeyRequest,
): string {
  return JSON.stringify(
    DeleteCustomMetadataFieldDefinitionsKeyRequest$outboundSchema.parse(
      deleteCustomMetadataFieldDefinitionsKeyRequest,
    ),
  );
}

/** @internal */
export const DeleteCustomMetadataFieldDefinitionsKeyCode$inboundSchema:
  z.ZodNativeEnum<typeof DeleteCustomMetadataFieldDefinitionsKeyCode> = z
    .nativeEnum(DeleteCustomMetadataFieldDefinitionsKeyCode);
