/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8e7cf39a6cc7
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteProjectsProjectIdSubfoldersSubfolderIdRequest = {
  /**
   * The hashed ID of the project
   */
  projectId: string;
  /**
   * The hashed ID of the subfolder
   */
  subfolderId: string;
};

/**
 * A subfolder within a project that contains media files.
 */
export type DeleteProjectsProjectIdSubfoldersSubfolderIdResponse = {
  /**
   * A unique alphanumeric identifier for this subfolder.
   */
  hashedId: string;
  /**
   * The display name of the subfolder.
   */
  name?: string | null | undefined;
  /**
   * A description for the subfolder.
   */
  description?: string | null | undefined;
  /**
   * The position of this subfolder within its project, used for ordering.
   */
  position: number | null;
  /**
   * The date when the subfolder was created.
   */
  created: Date | null;
  /**
   * The date when the subfolder was last modified.
   */
  updated: Date | null;
};

/** @internal */
export type DeleteProjectsProjectIdSubfoldersSubfolderIdRequest$Outbound = {
  projectId: string;
  subfolderId: string;
};

/** @internal */
export const DeleteProjectsProjectIdSubfoldersSubfolderIdRequest$outboundSchema:
  z.ZodType<
    DeleteProjectsProjectIdSubfoldersSubfolderIdRequest$Outbound,
    z.ZodTypeDef,
    DeleteProjectsProjectIdSubfoldersSubfolderIdRequest
  > = z.object({
    projectId: z.string(),
    subfolderId: z.string(),
  });

export function deleteProjectsProjectIdSubfoldersSubfolderIdRequestToJSON(
  deleteProjectsProjectIdSubfoldersSubfolderIdRequest:
    DeleteProjectsProjectIdSubfoldersSubfolderIdRequest,
): string {
  return JSON.stringify(
    DeleteProjectsProjectIdSubfoldersSubfolderIdRequest$outboundSchema.parse(
      deleteProjectsProjectIdSubfoldersSubfolderIdRequest,
    ),
  );
}

/** @internal */
export const DeleteProjectsProjectIdSubfoldersSubfolderIdResponse$inboundSchema:
  z.ZodType<
    DeleteProjectsProjectIdSubfoldersSubfolderIdResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    hashed_id: z.string(),
    name: z.nullable(z.string()).optional(),
    description: z.nullable(z.string()).optional(),
    position: z.nullable(z.number().int()),
    created: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ),
    updated: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ),
  }).transform((v) => {
    return remap$(v, {
      "hashed_id": "hashedId",
    });
  });

export function deleteProjectsProjectIdSubfoldersSubfolderIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteProjectsProjectIdSubfoldersSubfolderIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteProjectsProjectIdSubfoldersSubfolderIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteProjectsProjectIdSubfoldersSubfolderIdResponse' from JSON`,
  );
}
