/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { RFCDate } from "../../types/rfcdate.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * How to match the path of `embed_url` against embed locations. `exact` requires the path to match exactly; `prefix` matches any embed path starting with it.
 */
export const PathMatch = {
  Exact: "exact",
  Prefix: "prefix",
} as const;
/**
 * How to match the path of `embed_url` against embed locations. `exact` requires the path to match exactly; `prefix` matches any embed path starting with it.
 */
export type PathMatch = ClosedEnum<typeof PathMatch>;

export type GetAnalyticsAccountMediaByEmbedLocationRequest = {
  /**
   * The URL of the page to look up, e.g. `https://example.com/pricing`. The protocol is optional (https is assumed), so `example.com/pricing` also works.
   */
  embedUrl: string;
  /**
   * Start date for the analytics period in ISO 8601 format (YYYY-MM-DD). Inclusive — the range starts at the beginning of this date. Must be within the last 6 months. Defaults to 6 months ago, the start of the queryable window.
   */
  startDate?: RFCDate | undefined;
  /**
   * End date for the analytics period in ISO 8601 format (YYYY-MM-DD). Exclusive — the range ends before the beginning of this date. Defaults to tomorrow, so today's activity is included.
   */
  endDate?: RFCDate | undefined;
  /**
   * How to match the path of `embed_url` against embed locations. `exact` requires the path to match exactly; `prefix` matches any embed path starting with it.
   */
  pathMatch?: PathMatch | undefined;
  /**
   * Number of media hashed IDs to return (max 1000).
   */
  perPage?: number | undefined;
};

/**
 * A machine-readable identifier for the specific authorization failure.
 */
export const GetAnalyticsAccountMediaByEmbedLocationCode = {
  UnauthorizedCredentials: "unauthorized_credentials",
  AccountInactive: "account_inactive",
  UnauthorizedScope: "unauthorized_scope",
  UnauthorizedParams: "unauthorized_params",
} as const;
/**
 * A machine-readable identifier for the specific authorization failure.
 */
export type GetAnalyticsAccountMediaByEmbedLocationCode = ClosedEnum<
  typeof GetAnalyticsAccountMediaByEmbedLocationCode
>;

/**
 * Success response with the hashed IDs of media embedded at the location.
 */
export type GetAnalyticsAccountMediaByEmbedLocationResponse = {
  /**
   * Hashed IDs of media embedded at the location, ranked by plays.
   */
  mediaHashedIds?: Array<string> | undefined;
};

/** @internal */
export const PathMatch$outboundSchema: z.ZodNativeEnum<typeof PathMatch> = z
  .nativeEnum(PathMatch);

/** @internal */
export type GetAnalyticsAccountMediaByEmbedLocationRequest$Outbound = {
  embed_url: string;
  start_date?: string | undefined;
  end_date?: string | undefined;
  path_match: string;
  per_page: number;
};

/** @internal */
export const GetAnalyticsAccountMediaByEmbedLocationRequest$outboundSchema:
  z.ZodType<
    GetAnalyticsAccountMediaByEmbedLocationRequest$Outbound,
    z.ZodTypeDef,
    GetAnalyticsAccountMediaByEmbedLocationRequest
  > = z.object({
    embedUrl: z.string(),
    startDate: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
    endDate: z.instanceof(RFCDate).transform(v => v.toString()).optional(),
    pathMatch: PathMatch$outboundSchema.default("exact"),
    perPage: z.number().int().default(100),
  }).transform((v) => {
    return remap$(v, {
      embedUrl: "embed_url",
      startDate: "start_date",
      endDate: "end_date",
      pathMatch: "path_match",
      perPage: "per_page",
    });
  });

export function getAnalyticsAccountMediaByEmbedLocationRequestToJSON(
  getAnalyticsAccountMediaByEmbedLocationRequest:
    GetAnalyticsAccountMediaByEmbedLocationRequest,
): string {
  return JSON.stringify(
    GetAnalyticsAccountMediaByEmbedLocationRequest$outboundSchema.parse(
      getAnalyticsAccountMediaByEmbedLocationRequest,
    ),
  );
}

/** @internal */
export const GetAnalyticsAccountMediaByEmbedLocationCode$inboundSchema:
  z.ZodNativeEnum<typeof GetAnalyticsAccountMediaByEmbedLocationCode> = z
    .nativeEnum(GetAnalyticsAccountMediaByEmbedLocationCode);

/** @internal */
export const GetAnalyticsAccountMediaByEmbedLocationResponse$inboundSchema:
  z.ZodType<
    GetAnalyticsAccountMediaByEmbedLocationResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    media_hashed_ids: z.array(z.string()).optional(),
  }).transform((v) => {
    return remap$(v, {
      "media_hashed_ids": "mediaHashedIds",
    });
  });

export function getAnalyticsAccountMediaByEmbedLocationResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetAnalyticsAccountMediaByEmbedLocationResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetAnalyticsAccountMediaByEmbedLocationResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetAnalyticsAccountMediaByEmbedLocationResponse' from JSON`,
  );
}
