/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A machine-readable identifier for the specific authorization failure.
 */
export const GetBrandKitColorsCode = {
  UnauthorizedCredentials: "unauthorized_credentials",
  AccountInactive: "account_inactive",
  UnauthorizedScope: "unauthorized_scope",
  UnauthorizedParams: "unauthorized_params",
} as const;
/**
 * A machine-readable identifier for the specific authorization failure.
 */
export type GetBrandKitColorsCode = ClosedEnum<typeof GetBrandKitColorsCode>;

export type Color = {
  /**
   * The brand kit token's name, or the brand and field (e.g. "Acme primary color").
   */
  name: string;
  /**
   * Six-digit hex color with a leading "#" (e.g. "#2949E5").
   */
  value: string;
};

export type Stop = {
  /**
   * Six-digit hex color with a leading "#".
   */
  color: string;
  /**
   * Where the stop sits along the gradient, as stored on the brand.
   */
  position: number;
};

export type BrandGradient = {
  /**
   * The brand and field the gradient comes from (e.g. "Acme primary color").
   */
  name: string;
  /**
   * The gradient's color stops, sorted by position.
   */
  stops: Array<Stop>;
};

/**
 * The current account's brand colors, from its brand kits and its brands.
 */
export type GetBrandKitColorsResponse = {
  /**
   * Solid brand colors: every brand kit's color tokens (newest kit
   *
   * @remarks
   * first, tokens in the order they were added), then each brand's
   * primary and page background color when it is a solid color
   * (default brand first). A color already listed isn't repeated.
   * Empty when the account has none.
   */
  colors: Array<Color>;
  /**
   * Each brand's primary and page background color that is set to a
   *
   * @remarks
   * gradient, default brand first. Stops whose color isn't a hex color
   * are left out, and a gradient with fewer than two hex stops left
   * isn't listed. Empty when none are gradients.
   */
  brandGradients: Array<BrandGradient>;
};

/** @internal */
export const GetBrandKitColorsCode$inboundSchema: z.ZodNativeEnum<
  typeof GetBrandKitColorsCode
> = z.nativeEnum(GetBrandKitColorsCode);

/** @internal */
export const Color$inboundSchema: z.ZodType<Color, z.ZodTypeDef, unknown> = z
  .object({
    name: z.string(),
    value: z.string(),
  });

export function colorFromJSON(
  jsonString: string,
): SafeParseResult<Color, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Color$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Color' from JSON`,
  );
}

/** @internal */
export const Stop$inboundSchema: z.ZodType<Stop, z.ZodTypeDef, unknown> = z
  .object({
    color: z.string(),
    position: z.number(),
  });

export function stopFromJSON(
  jsonString: string,
): SafeParseResult<Stop, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Stop$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Stop' from JSON`,
  );
}

/** @internal */
export const BrandGradient$inboundSchema: z.ZodType<
  BrandGradient,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  stops: z.array(z.lazy(() => Stop$inboundSchema)),
});

export function brandGradientFromJSON(
  jsonString: string,
): SafeParseResult<BrandGradient, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BrandGradient$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BrandGradient' from JSON`,
  );
}

/** @internal */
export const GetBrandKitColorsResponse$inboundSchema: z.ZodType<
  GetBrandKitColorsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  colors: z.array(z.lazy(() => Color$inboundSchema)),
  brand_gradients: z.array(z.lazy(() => BrandGradient$inboundSchema)),
}).transform((v) => {
  return remap$(v, {
    "brand_gradients": "brandGradients",
  });
});

export function getBrandKitColorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBrandKitColorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBrandKitColorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBrandKitColorsResponse' from JSON`,
  );
}
