/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 * @generated-id: 8db2eb890b51
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdGlobals = {
  /**
   * The API version
   */
  xWistiaAPIVersion?: string | undefined;
};

export type GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdRequest = {
  /**
   * The hashed ID of the channel.
   */
  channelHashedId: string;
  /**
   * The hashed ID of the channel episode.
   */
  channelEpisodeId: string;
  /**
   * The API version
   */
  xWistiaAPIVersion?: string | undefined;
};

/**
 * Channel Episode retrieval successful
 */
export type GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdResponse =
  {
    /**
     * A unique alphanumeric identifier for the channel episode's channel.
     */
    channelHashedId: string;
    /**
     * The date when the channel episode was originally created.
     */
    created: Date;
    /**
     * The channel episode's description or episode notes.
     */
    description: string;
    /**
     * A short summary of the episode that is displayed when space is limited.
     */
    summary: string;
    /**
     * A unique alphanumeric identifier for the channel episode.
     */
    hashedId: string;
    /**
     * A unique alphanumeric identifier for the channel episode's media.
     */
    mediaHashedId: string;
    /**
     * Whether the channel episode has been published or is still in draft form.
     */
    published: boolean;
    /**
     * The date and time when the episode is scheduled to be published in UTC timezone (only present when publish_status is 'scheduled').
     */
    publishAt?: Date | undefined;
    /**
     * The title of the channel episode
     */
    title: string | null;
    /**
     * The date when the channel was last updated.
     */
    updated: Date;
  };

/** @internal */
export type GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdRequest$Outbound =
  {
    channelHashedId: string;
    channelEpisodeId: string;
    "X-Wistia-API-Version"?: string | undefined;
  };

/** @internal */
export const GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdRequest$outboundSchema:
  z.ZodType<
    GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdRequest$Outbound,
    z.ZodTypeDef,
    GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdRequest
  > = z.object({
    channelHashedId: z.string(),
    channelEpisodeId: z.string(),
    xWistiaAPIVersion: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      xWistiaAPIVersion: "X-Wistia-API-Version",
    });
  });

export function getChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdRequestToJSON(
  getChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdRequest:
    GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdRequest,
): string {
  return JSON.stringify(
    GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdRequest$outboundSchema
      .parse(getChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdRequest),
  );
}

/** @internal */
export const GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdResponse$inboundSchema:
  z.ZodType<
    GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    channelHashedId: z.string(),
    created: z.string().datetime({ offset: true }).transform(v => new Date(v)),
    description: z.string(),
    summary: z.string(),
    hashedId: z.string(),
    mediaHashedId: z.string(),
    published: z.boolean(),
    publish_at: z.string().datetime({ offset: true }).transform(v =>
      new Date(v)
    ).optional(),
    title: z.nullable(z.string()),
    updated: z.string().datetime({ offset: true }).transform(v => new Date(v)),
  }).transform((v) => {
    return remap$(v, {
      "publish_at": "publishAt",
    });
  });

export function getChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetChannelsChannelHashedIdChannelEpisodesChannelEpisodeIdResponse' from JSON`,
  );
}
