/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The kind of resource the hashed ID refers to.
 */
export const GetResourceUrlsType = {
  Media: "media",
  Folder: "folder",
  Channel: "channel",
  ChannelEpisode: "channel_episode",
  Webinar: "webinar",
  Remix: "remix",
} as const;
/**
 * The kind of resource the hashed ID refers to.
 */
export type GetResourceUrlsType = ClosedEnum<typeof GetResourceUrlsType>;

export type GetResourceUrlsRequest = {
  /**
   * The kind of resource the hashed ID refers to.
   */
  type: GetResourceUrlsType;
  /**
   * The hashed ID of the resource.
   */
  hashedId: string;
};

/**
 * A machine-readable identifier for the specific authorization failure.
 */
export const GetResourceUrlsCode = {
  UnauthorizedCredentials: "unauthorized_credentials",
  AccountInactive: "account_inactive",
  UnauthorizedScope: "unauthorized_scope",
  UnauthorizedParams: "unauthorized_params",
} as const;
/**
 * A machine-readable identifier for the specific authorization failure.
 */
export type GetResourceUrlsCode = ClosedEnum<typeof GetResourceUrlsCode>;

/**
 * The resource's canonical app URLs, keyed by kind.
 */
export type Urls = {
  /**
   * The page where the resource is viewed.
   */
  show: string;
};

/**
 * The resource's canonical URLs
 */
export type GetResourceUrlsResponse = {
  /**
   * The kind of resource that was resolved.
   */
  type: string;
  /**
   * The hashed ID of the resolved resource.
   */
  hashedId: string;
  /**
   * The resource's canonical app URLs, keyed by kind.
   */
  urls: Urls;
};

/** @internal */
export const GetResourceUrlsType$outboundSchema: z.ZodNativeEnum<
  typeof GetResourceUrlsType
> = z.nativeEnum(GetResourceUrlsType);

/** @internal */
export type GetResourceUrlsRequest$Outbound = {
  type: string;
  hashed_id: string;
};

/** @internal */
export const GetResourceUrlsRequest$outboundSchema: z.ZodType<
  GetResourceUrlsRequest$Outbound,
  z.ZodTypeDef,
  GetResourceUrlsRequest
> = z.object({
  type: GetResourceUrlsType$outboundSchema,
  hashedId: z.string(),
}).transform((v) => {
  return remap$(v, {
    hashedId: "hashed_id",
  });
});

export function getResourceUrlsRequestToJSON(
  getResourceUrlsRequest: GetResourceUrlsRequest,
): string {
  return JSON.stringify(
    GetResourceUrlsRequest$outboundSchema.parse(getResourceUrlsRequest),
  );
}

/** @internal */
export const GetResourceUrlsCode$inboundSchema: z.ZodNativeEnum<
  typeof GetResourceUrlsCode
> = z.nativeEnum(GetResourceUrlsCode);

/** @internal */
export const Urls$inboundSchema: z.ZodType<Urls, z.ZodTypeDef, unknown> = z
  .object({
    show: z.string(),
  });

export function urlsFromJSON(
  jsonString: string,
): SafeParseResult<Urls, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Urls$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Urls' from JSON`,
  );
}

/** @internal */
export const GetResourceUrlsResponse$inboundSchema: z.ZodType<
  GetResourceUrlsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.string(),
  hashed_id: z.string(),
  urls: z.lazy(() => Urls$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "hashed_id": "hashedId",
  });
});

export function getResourceUrlsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetResourceUrlsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetResourceUrlsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetResourceUrlsResponse' from JSON`,
  );
}
