/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * A machine-readable identifier for the specific authorization failure.
 */
export const GetRemixAccountStatusCode = {
  UnauthorizedCredentials: "unauthorized_credentials",
  AccountInactive: "account_inactive",
  UnauthorizedScope: "unauthorized_scope",
  UnauthorizedParams: "unauthorized_params",
} as const;
/**
 * A machine-readable identifier for the specific authorization failure.
 */
export type GetRemixAccountStatusCode = ClosedEnum<
  typeof GetRemixAccountStatusCode
>;

/**
 * Whether Remix uses Credits or the legacy monthly allowance.
 */
export const GetRemixAccountStatusBillingMode = {
  Credits: "credits",
  MonthlyLimit: "monthly_limit",
} as const;
/**
 * Whether Remix uses Credits or the legacy monthly allowance.
 */
export type GetRemixAccountStatusBillingMode = ClosedEnum<
  typeof GetRemixAccountStatusBillingMode
>;

/**
 * Remix account status.
 */
export type GetRemixAccountStatusResponse = {
  /**
   * Whether Remix uses Credits or the legacy monthly allowance.
   */
  billingMode?: GetRemixAccountStatusBillingMode | undefined;
  /**
   * Legacy monthly Remix allowance. Does not determine affordability in Credits mode.
   */
  monthlyLimit?: number | undefined;
  /**
   * Number of Remixes counted toward the legacy monthly allowance.
   */
  monthlyUsage?: number | undefined;
  /**
   * Remaining legacy monthly allowance. Does not determine affordability in Credits mode.
   */
  remaining?: number | undefined;
  /**
   * Whether the account has enough Credits or legacy monthly allowance to create or continue a Remix.
   */
  canCreateRemix?: boolean | undefined;
  /**
   * Available Credit balance, present in Credits mode.
   */
  creditBalance?: number | undefined;
  /**
   * Account-specific Credit cost of one Remix creation or iteration, present in Credits mode.
   */
  remixCreditCost?: number | undefined;
  /**
   * Next scheduled plan Credit grant (ISO 8601), when available in Credits mode.
   */
  creditsRenewAt?: Date | undefined;
};

/** @internal */
export const GetRemixAccountStatusCode$inboundSchema: z.ZodNativeEnum<
  typeof GetRemixAccountStatusCode
> = z.nativeEnum(GetRemixAccountStatusCode);

/** @internal */
export const GetRemixAccountStatusBillingMode$inboundSchema: z.ZodNativeEnum<
  typeof GetRemixAccountStatusBillingMode
> = z.nativeEnum(GetRemixAccountStatusBillingMode);

/** @internal */
export const GetRemixAccountStatusResponse$inboundSchema: z.ZodType<
  GetRemixAccountStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  billing_mode: GetRemixAccountStatusBillingMode$inboundSchema.optional(),
  monthly_limit: z.number().int().optional(),
  monthly_usage: z.number().int().optional(),
  remaining: z.number().int().optional(),
  can_create_remix: z.boolean().optional(),
  credit_balance: z.number().optional(),
  remix_credit_cost: z.number().optional(),
  credits_renew_at: z.string().datetime({ offset: true }).transform(v =>
    new Date(v)
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    "billing_mode": "billingMode",
    "monthly_limit": "monthlyLimit",
    "monthly_usage": "monthlyUsage",
    "can_create_remix": "canCreateRemix",
    "credit_balance": "creditBalance",
    "remix_credit_cost": "remixCreditCost",
    "credits_renew_at": "creditsRenewAt",
  });
});

export function getRemixAccountStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetRemixAccountStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRemixAccountStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRemixAccountStatusResponse' from JSON`,
  );
}
