/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostRemixesRequest = {
  /**
   * Array of source media hashed IDs to remix from.
   */
  mediaHashedIds: Array<string>;
  /**
   * Natural language instructions describing the desired remix (e.g., "create a 60-second highlight reel").
   */
  instructions: string;
};

/**
 * Current status of the remix job.
 */
export const PostRemixesStatus = {
  Pending: "pending",
  Deferred: "deferred",
} as const;
/**
 * Current status of the remix job.
 */
export type PostRemixesStatus = ClosedEnum<typeof PostRemixesStatus>;

export type PostRemixesSourceMedia = {
  hashedId?: string | undefined;
  name?: string | undefined;
};

/**
 * Remix job successfully created.
 */
export type PostRemixesResponse = {
  /**
   * Hashed ID of the created remix. Use this to poll for status.
   */
  remixId?: string | undefined;
  /**
   * Hashed ID of the remix conversation (groups multiple remix iterations).
   */
  conversationId?: string | undefined;
  /**
   * Current status of the remix job.
   */
  status?: PostRemixesStatus | undefined;
  /**
   * The source media used for this remix.
   */
  sourceMedias?: Array<PostRemixesSourceMedia> | undefined;
};

/** @internal */
export type PostRemixesRequest$Outbound = {
  media_hashed_ids: Array<string>;
  instructions: string;
};

/** @internal */
export const PostRemixesRequest$outboundSchema: z.ZodType<
  PostRemixesRequest$Outbound,
  z.ZodTypeDef,
  PostRemixesRequest
> = z.object({
  mediaHashedIds: z.array(z.string()),
  instructions: z.string(),
}).transform((v) => {
  return remap$(v, {
    mediaHashedIds: "media_hashed_ids",
  });
});

export function postRemixesRequestToJSON(
  postRemixesRequest: PostRemixesRequest,
): string {
  return JSON.stringify(
    PostRemixesRequest$outboundSchema.parse(postRemixesRequest),
  );
}

/** @internal */
export const PostRemixesStatus$inboundSchema: z.ZodNativeEnum<
  typeof PostRemixesStatus
> = z.nativeEnum(PostRemixesStatus);

/** @internal */
export const PostRemixesSourceMedia$inboundSchema: z.ZodType<
  PostRemixesSourceMedia,
  z.ZodTypeDef,
  unknown
> = z.object({
  hashed_id: z.string().optional(),
  name: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "hashed_id": "hashedId",
  });
});

export function postRemixesSourceMediaFromJSON(
  jsonString: string,
): SafeParseResult<PostRemixesSourceMedia, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostRemixesSourceMedia$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostRemixesSourceMedia' from JSON`,
  );
}

/** @internal */
export const PostRemixesResponse$inboundSchema: z.ZodType<
  PostRemixesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  remix_id: z.string().optional(),
  conversation_id: z.string().optional(),
  status: PostRemixesStatus$inboundSchema.optional(),
  source_medias: z.array(z.lazy(() => PostRemixesSourceMedia$inboundSchema))
    .optional(),
}).transform((v) => {
  return remap$(v, {
    "remix_id": "remixId",
    "conversation_id": "conversationId",
    "source_medias": "sourceMedias",
  });
});

export function postRemixesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostRemixesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostRemixesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostRemixesResponse' from JSON`,
  );
}
