/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostRemixesRemixHashedIdContinueRequestBody = {
  /**
   * Natural language instructions for the edit (e.g., "cut the first 10 seconds").
   */
  instructions: string;
};

export type PostRemixesRemixHashedIdContinueRequest = {
  /**
   * The hashed ID of the current remix version to edit from.
   */
  remixHashedId: string;
  requestBody?: PostRemixesRemixHashedIdContinueRequestBody | undefined;
};

/**
 * Status of the new remix version.
 */
export const PostRemixesRemixHashedIdContinueStatus = {
  Pending: "pending",
} as const;
/**
 * Status of the new remix version.
 */
export type PostRemixesRemixHashedIdContinueStatus = ClosedEnum<
  typeof PostRemixesRemixHashedIdContinueStatus
>;

/**
 * New remix version created.
 */
export type PostRemixesRemixHashedIdContinueResponse = {
  /**
   * Hashed ID of the new remix version.
   */
  remixId?: string | undefined;
  /**
   * Hashed ID of the conversation.
   */
  conversationId?: string | undefined;
  /**
   * Status of the new remix version.
   */
  status?: PostRemixesRemixHashedIdContinueStatus | undefined;
  /**
   * Hashed ID of the remix version this edit is based on.
   */
  previousRemixId?: string | undefined;
};

/** @internal */
export type PostRemixesRemixHashedIdContinueRequestBody$Outbound = {
  instructions: string;
};

/** @internal */
export const PostRemixesRemixHashedIdContinueRequestBody$outboundSchema:
  z.ZodType<
    PostRemixesRemixHashedIdContinueRequestBody$Outbound,
    z.ZodTypeDef,
    PostRemixesRemixHashedIdContinueRequestBody
  > = z.object({
    instructions: z.string(),
  });

export function postRemixesRemixHashedIdContinueRequestBodyToJSON(
  postRemixesRemixHashedIdContinueRequestBody:
    PostRemixesRemixHashedIdContinueRequestBody,
): string {
  return JSON.stringify(
    PostRemixesRemixHashedIdContinueRequestBody$outboundSchema.parse(
      postRemixesRemixHashedIdContinueRequestBody,
    ),
  );
}

/** @internal */
export type PostRemixesRemixHashedIdContinueRequest$Outbound = {
  remixHashedId: string;
  RequestBody?:
    | PostRemixesRemixHashedIdContinueRequestBody$Outbound
    | undefined;
};

/** @internal */
export const PostRemixesRemixHashedIdContinueRequest$outboundSchema: z.ZodType<
  PostRemixesRemixHashedIdContinueRequest$Outbound,
  z.ZodTypeDef,
  PostRemixesRemixHashedIdContinueRequest
> = z.object({
  remixHashedId: z.string(),
  requestBody: z.lazy(() =>
    PostRemixesRemixHashedIdContinueRequestBody$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function postRemixesRemixHashedIdContinueRequestToJSON(
  postRemixesRemixHashedIdContinueRequest:
    PostRemixesRemixHashedIdContinueRequest,
): string {
  return JSON.stringify(
    PostRemixesRemixHashedIdContinueRequest$outboundSchema.parse(
      postRemixesRemixHashedIdContinueRequest,
    ),
  );
}

/** @internal */
export const PostRemixesRemixHashedIdContinueStatus$inboundSchema:
  z.ZodNativeEnum<typeof PostRemixesRemixHashedIdContinueStatus> = z.nativeEnum(
    PostRemixesRemixHashedIdContinueStatus,
  );

/** @internal */
export const PostRemixesRemixHashedIdContinueResponse$inboundSchema: z.ZodType<
  PostRemixesRemixHashedIdContinueResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  remix_id: z.string().optional(),
  conversation_id: z.string().optional(),
  status: PostRemixesRemixHashedIdContinueStatus$inboundSchema.optional(),
  previous_remix_id: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    "remix_id": "remixId",
    "conversation_id": "conversationId",
    "previous_remix_id": "previousRemixId",
  });
});

export function postRemixesRemixHashedIdContinueResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostRemixesRemixHashedIdContinueResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostRemixesRemixHashedIdContinueResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostRemixesRemixHashedIdContinueResponse' from JSON`,
  );
}
