/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Updated subfolder data
 */
export type PutProjectsProjectIdSubfoldersSubfolderIdRequestBody = {
  /**
   * The new name for the subfolder
   */
  name?: string | undefined;
  /**
   * The new description for the subfolder
   */
  description?: string | null | undefined;
};

export type PutProjectsProjectIdSubfoldersSubfolderIdRequest = {
  /**
   * The hashed ID of the project
   */
  projectId: string;
  /**
   * The hashed ID of the subfolder
   */
  subfolderId: string;
  /**
   * Updated subfolder data
   */
  requestBody: PutProjectsProjectIdSubfoldersSubfolderIdRequestBody;
};

/**
 * A subfolder within a project that contains media files.
 */
export type PutProjectsProjectIdSubfoldersSubfolderIdResponse = {
  /**
   * A unique alphanumeric identifier for this subfolder.
   */
  hashedId: string;
  /**
   * The display name of the subfolder.
   */
  name?: string | null | undefined;
  /**
   * A description for the subfolder.
   */
  description?: string | null | undefined;
  /**
   * The position of this subfolder within its project, used for ordering.
   */
  position: number | null;
  /**
   * The date when the subfolder was created.
   */
  created: Date | null;
  /**
   * The date when the subfolder was last modified.
   */
  updated: Date | null;
};

/** @internal */
export const PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$inboundSchema:
  z.ZodType<
    PutProjectsProjectIdSubfoldersSubfolderIdRequestBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    name: z.string().optional(),
    description: z.nullable(z.string()).optional(),
  });

/** @internal */
export type PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$Outbound = {
  name?: string | undefined;
  description?: string | null | undefined;
};

/** @internal */
export const PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$outboundSchema:
  z.ZodType<
    PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$Outbound,
    z.ZodTypeDef,
    PutProjectsProjectIdSubfoldersSubfolderIdRequestBody
  > = z.object({
    name: z.string().optional(),
    description: z.nullable(z.string()).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$ {
  /** @deprecated use `PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$inboundSchema;
  /** @deprecated use `PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$outboundSchema;
  /** @deprecated use `PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$Outbound` instead. */
  export type Outbound =
    PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$Outbound;
}

export function putProjectsProjectIdSubfoldersSubfolderIdRequestBodyToJSON(
  putProjectsProjectIdSubfoldersSubfolderIdRequestBody:
    PutProjectsProjectIdSubfoldersSubfolderIdRequestBody,
): string {
  return JSON.stringify(
    PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$outboundSchema.parse(
      putProjectsProjectIdSubfoldersSubfolderIdRequestBody,
    ),
  );
}

export function putProjectsProjectIdSubfoldersSubfolderIdRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<
  PutProjectsProjectIdSubfoldersSubfolderIdRequestBody,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PutProjectsProjectIdSubfoldersSubfolderIdRequestBody' from JSON`,
  );
}

/** @internal */
export const PutProjectsProjectIdSubfoldersSubfolderIdRequest$inboundSchema:
  z.ZodType<
    PutProjectsProjectIdSubfoldersSubfolderIdRequest,
    z.ZodTypeDef,
    unknown
  > = z.object({
    projectId: z.string(),
    subfolderId: z.string(),
    RequestBody: z.lazy(() =>
      PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$inboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      "RequestBody": "requestBody",
    });
  });

/** @internal */
export type PutProjectsProjectIdSubfoldersSubfolderIdRequest$Outbound = {
  projectId: string;
  subfolderId: string;
  RequestBody: PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$Outbound;
};

/** @internal */
export const PutProjectsProjectIdSubfoldersSubfolderIdRequest$outboundSchema:
  z.ZodType<
    PutProjectsProjectIdSubfoldersSubfolderIdRequest$Outbound,
    z.ZodTypeDef,
    PutProjectsProjectIdSubfoldersSubfolderIdRequest
  > = z.object({
    projectId: z.string(),
    subfolderId: z.string(),
    requestBody: z.lazy(() =>
      PutProjectsProjectIdSubfoldersSubfolderIdRequestBody$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      requestBody: "RequestBody",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutProjectsProjectIdSubfoldersSubfolderIdRequest$ {
  /** @deprecated use `PutProjectsProjectIdSubfoldersSubfolderIdRequest$inboundSchema` instead. */
  export const inboundSchema =
    PutProjectsProjectIdSubfoldersSubfolderIdRequest$inboundSchema;
  /** @deprecated use `PutProjectsProjectIdSubfoldersSubfolderIdRequest$outboundSchema` instead. */
  export const outboundSchema =
    PutProjectsProjectIdSubfoldersSubfolderIdRequest$outboundSchema;
  /** @deprecated use `PutProjectsProjectIdSubfoldersSubfolderIdRequest$Outbound` instead. */
  export type Outbound =
    PutProjectsProjectIdSubfoldersSubfolderIdRequest$Outbound;
}

export function putProjectsProjectIdSubfoldersSubfolderIdRequestToJSON(
  putProjectsProjectIdSubfoldersSubfolderIdRequest:
    PutProjectsProjectIdSubfoldersSubfolderIdRequest,
): string {
  return JSON.stringify(
    PutProjectsProjectIdSubfoldersSubfolderIdRequest$outboundSchema.parse(
      putProjectsProjectIdSubfoldersSubfolderIdRequest,
    ),
  );
}

export function putProjectsProjectIdSubfoldersSubfolderIdRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  PutProjectsProjectIdSubfoldersSubfolderIdRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PutProjectsProjectIdSubfoldersSubfolderIdRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PutProjectsProjectIdSubfoldersSubfolderIdRequest' from JSON`,
  );
}

/** @internal */
export const PutProjectsProjectIdSubfoldersSubfolderIdResponse$inboundSchema:
  z.ZodType<
    PutProjectsProjectIdSubfoldersSubfolderIdResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    hashed_id: z.string(),
    name: z.nullable(z.string()).optional(),
    description: z.nullable(z.string()).optional(),
    position: z.nullable(z.number().int()),
    created: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ),
    updated: z.nullable(
      z.string().datetime({ offset: true }).transform(v => new Date(v)),
    ),
  }).transform((v) => {
    return remap$(v, {
      "hashed_id": "hashedId",
    });
  });

/** @internal */
export type PutProjectsProjectIdSubfoldersSubfolderIdResponse$Outbound = {
  hashed_id: string;
  name?: string | null | undefined;
  description?: string | null | undefined;
  position: number | null;
  created: string | null;
  updated: string | null;
};

/** @internal */
export const PutProjectsProjectIdSubfoldersSubfolderIdResponse$outboundSchema:
  z.ZodType<
    PutProjectsProjectIdSubfoldersSubfolderIdResponse$Outbound,
    z.ZodTypeDef,
    PutProjectsProjectIdSubfoldersSubfolderIdResponse
  > = z.object({
    hashedId: z.string(),
    name: z.nullable(z.string()).optional(),
    description: z.nullable(z.string()).optional(),
    position: z.nullable(z.number().int()),
    created: z.nullable(z.date().transform(v => v.toISOString())),
    updated: z.nullable(z.date().transform(v => v.toISOString())),
  }).transform((v) => {
    return remap$(v, {
      hashedId: "hashed_id",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PutProjectsProjectIdSubfoldersSubfolderIdResponse$ {
  /** @deprecated use `PutProjectsProjectIdSubfoldersSubfolderIdResponse$inboundSchema` instead. */
  export const inboundSchema =
    PutProjectsProjectIdSubfoldersSubfolderIdResponse$inboundSchema;
  /** @deprecated use `PutProjectsProjectIdSubfoldersSubfolderIdResponse$outboundSchema` instead. */
  export const outboundSchema =
    PutProjectsProjectIdSubfoldersSubfolderIdResponse$outboundSchema;
  /** @deprecated use `PutProjectsProjectIdSubfoldersSubfolderIdResponse$Outbound` instead. */
  export type Outbound =
    PutProjectsProjectIdSubfoldersSubfolderIdResponse$Outbound;
}

export function putProjectsProjectIdSubfoldersSubfolderIdResponseToJSON(
  putProjectsProjectIdSubfoldersSubfolderIdResponse:
    PutProjectsProjectIdSubfoldersSubfolderIdResponse,
): string {
  return JSON.stringify(
    PutProjectsProjectIdSubfoldersSubfolderIdResponse$outboundSchema.parse(
      putProjectsProjectIdSubfoldersSubfolderIdResponse,
    ),
  );
}

export function putProjectsProjectIdSubfoldersSubfolderIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PutProjectsProjectIdSubfoldersSubfolderIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PutProjectsProjectIdSubfoldersSubfolderIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PutProjectsProjectIdSubfoldersSubfolderIdResponse' from JSON`,
  );
}
